### ISSUE TITLE
Can not find image trailofbits/slither:latest

### ISSUE THREAD

**Issue by nbhkf** [smartbugs/smartbugs#13]
I want to use slither to check the contract, but I got this information, I hope you can help, thank you！

Analysing file [0/1]: dataset/denial_of_service/auction.sol [slither]
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2
404 Client Error: Not Found ("No such image: trailofbits/slither:latest")
unsupported operand type(s) for +: 'ImageNotFound' and 'str'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 785, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: trailofbits/slither:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangkaifeng/Desktop/smartbugs/src/docker_api/docker_api.py", line 240, in analyse_files
    volumes=volume_bindings)
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 789, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: trailofbits/slither:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "smartBugs.py", line 60, in analyse
    raise e
  File "smartBugs.py", line 40, in analyse
    analyse_files(tool, file, logs, output_folder)
  File "/Users/huangkaifeng/Desktop/smartbugs/src/docker_api/docker_api.py", line 259, in analyse_files
    logs.write(err + '\n' )
TypeError: unsupported operand type(s) for +: 'ImageNotFound' and 'str'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "smartBugs.py", line 120, in <module>
    logs = exec_cmd(args)
  File "smartBugs.py", line 112, in exec_cmd
    pool.map(analyse, tasks)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'ImageNotFound' and 'str'

**Comment by pedrocrvz** [comment]
This seems to be an issue related to the docker-py library ([#2101](https://github.com/docker/docker-py/issues/2101)).
Try to pull the image manually (`docker pull trailofbits/slither:latest`) and then re-run SmartBugs using the same command.

**Comment by nbhkf** [comment]
Thank you for your reply，can i fix it？



发自我的iPhone


------------------ Original ------------------

**Comment by pedrocrvz** [comment]
I am not sure what you mean by "fixing" it, since it's a library issue. But sure, we welcome any PR from people who want to contribute.

**Comment by nbhkf** [comment]
Thank you for your reply



发自我的iPhone


------------------ Original ------------------
