### ISSUE TITLE
exec: "/sb/bin/do_solidity": permission denied: unknown"

### ISSUE THREAD

**Issue by polanwind** [smartbugs/smartbugs#141]
when i run the cmd "./smartbugs -t confuzzius -f samples/*.sol", the error output is as following, how can i solve these problems and run the cmd successfully? Thanks for replying!!

error output:

./smartbugs: line 13: venv/bin/activate: No such file or directory
which: no solc in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ovo/.local/bin:/home/ovo/bin)
Welcome to SmartBugs 2.0.1!
Starting task 1/10: confuzzius and samples/simple_dao.sol
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/python3/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/6bc88b29fa181bac5f047c6c2119d4eacee9df382df9d606b02c577b945af173/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ovo/smartbugs2.0/sb/analysis.py", line 142, in analyser
    duration = execute(task)
  File "/home/ovo/smartbugs2.0/sb/analysis.py", line 88, in execute
    exit_code,tool_log,tool_output,docker_args = sb.docker.execute(task)
  File "/home/ovo/smartbugs2.0/sb/docker.py", line 82, in execute
    container = client().containers.run(**args)
  File "/usr/local/python3/lib/python3.6/site-packages/docker/models/containers.py", line 826, in run
    container.start()
  File "/usr/local/python3/lib/python3.6/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/docker/api/container.py", line 1109, in start
    self._raise_for_status(res)
  File "/usr/local/python3/lib/python3.6/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/python3/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/6bc88b29fa181bac5f047c6c2119d4eacee9df382df9d606b02c577b945af173/start: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/sb/bin/do_solidity": permission denied: unknown")
Analysis completed in 0:00:01.

**Comment by polanwind** [comment]
anyway this problem fixed
