### ISSUE TITLE
Docker: checking for image smartbugs/confuzzius:4315fb7 failed.

### ISSUE THREAD

**Issue by ds-rgangavasi** [smartbugs/smartbugs#183]
**Docker: checking for image smartbugs/confuzzius:4315fb7 failed.**
When I want to test sample files using smartbugs CLI, I invoke `./smartbugs -t all -f samples/SimpleDAO.sol` and get following output:

```
./smartbugs -t all -f samples/SimpleDAO.sol 
Welcome to SmartBugs 2.0.9!
Collecting files ...
1 files to analyse
Assembling tasks ...
Docker: checking for image smartbugs/confuzzius:4315fb7 failed.
Docker: Cannot connect to service. Is it installed and running?
```
**Platform**
- SmartBugs version: 2.0.9
- Python version: 3.11.7
- Operating System: Ubuntu 22.04.3 LTS                 
- Kernel: Linux 6.2.0-34-generic
- Architecture: x86-64
- Docker version: 26.1.2, build 211e74b

**Additional context**
- I tried to manually add images for smartbugs/confuzzius:4315fb7 or smartbugs/mythril:0.24.7 but nothing works. same error, everytime.

**Comment by gsalzer** [comment]
_"I tried to manually add images for smartbugs/confuzzius:4315fb7 or smartbugs/mythril:0.24.7 but nothing works. same error, everytime."_

This points towards a permission problem. Have you done the first item of the installation instructions, https://github.com/smartbugs/smartbugs?tab=readme-ov-file#unixlinux, adding your user to the `docker` group? As long as a command like
```console
docker pull smartbugs/confuzzius:4315fb7
```
from the command line fails, the issue is one of your Docker setup.

**Comment by ds-rgangavasi** [comment]
I have tried 
- sudo usermod -a -G docker $USER
- cd smartbugs
- sh install/setup-venv.sh (tried with sudo as well)
- ./smartbugs -t mythril -f samples/*.sol

returns docker error as mentioned above.

Can you please provide a github gist with docker file, where you can simply run this `smartbugs CLI` tool where I can attach some volume like below to run things e2e.

`docker run -it -v $(pwd):/tmp --name smartbugs-test-repo smartbugs sh`
`./smartbugs -t all -f samples/SimpleDAO.sol `

**Comment by gsalzer** [comment]
@ds-rgangavasi What is the output when you execute the command `docker pull smartbugs/confuzzius:4315fb7` from the command line?

**Comment by gsalzer** [comment]
@ds-rgangavasi Next, which output do you get when you run `./smartbugs` without any arguments, in the folder containing the smartbugs script?

**Comment by gsalzer** [comment]
@ds-rgangavasi Providing smartbugs itself as a docker image is an interesting idea. Last time I checked it was not recommended to run Docker within Docker (which would be necessary when dockerizing Smartbugs). I will check whether there are new developments in this respect.

Apart from that, Smartbugs currently needs access to the file system. This can be changed, but requires a rearrangement of the internal logic.

**Comment by ds-rgangavasi** [comment]
> docker pull smartbugs/confuzzius:4315fb7
Output for `docker pull smartbugs/confuzzius:4315fb7`
![image](https://github.com/smartbugs/smartbugs/assets/165517863/3d4d0beb-b3dc-4f5e-8215-1e47050d33a0)

Output for `docker images`:
![image](https://github.com/smartbugs/smartbugs/assets/165517863/ad4a6f3c-c9c4-4ee7-b2e1-728d8574059a)

**Comment by ds-rgangavasi** [comment]
> @ds-rgangavasi Next, which output do you get when you run `./smartbugs` without any arguments, in the folder containing the smartbugs script?

Output for `./smartbugs`
![image](https://github.com/smartbugs/smartbugs/assets/165517863/65a05ee1-542c-4c4b-bbc2-a3c1581f1ed1)

**Comment by gsalzer** [comment]
@ds-rgangavasi If you are still at it: Pull the newest SmartBugs commit, or just download the file `install/docker-test.py`, and run it:
```console
. venv/bin/activate # activate virtual environment
./install/docker-test.py
```
If everything works, you should see
```
get handle to communicate with docker
testing the communication
load a sample image
image hello-world has been loaded
run the container, retrieve the output, and print the second line
*** Hello from Docker! ***
cleaning up
```
Otherwise, please post the output (which probably will contain only a few lines from above and a trace).

If this test works, run SmartBugs with the additional flag `--debug`. It will initially list the version of many Python packages (in particular of the docker package), and will also produce a trace if the communication with docker fails.

**Comment by francescosalzano1** [comment]
@gsalzer I had the same issue, by the way, I was using an older version of Python than 3.9. Updating Python resolved this issue.

**Comment by gsalzer** [comment]
@francescosalzano1 Thanks, good to know.

**Comment by yashgoelnethermind** [comment]
@gsalzer Get a similar issue, I tried running "docker_test.py":
```
(venv) yashgoel@Yashs-MacBook-Air smartbugs % ./install/docker_test.py
get handle to communicate with docker
Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/./install/docker_test.py", line 6, in <module>
    client = docker.from_env()
             ^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 207, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by yashgoelnethermind** [comment]
@gsalzer Got a similar issue.....I tried running `docker_test.py` and got following error:
```
(venv) yashgoel@Yashs-MacBook-Air smartbugs % ./install/docker_test.py
get handle to communicate with docker
Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/smartbugs/./install/docker_test.py", line 6, in <module>
    client = docker.from_env()
             ^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 207, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/smartbugs/venv/lib/python3.12/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by ds-rgangavasi** [comment]
I removed my installed docker entirely, and re-installed, fixed my issue.
