### ISSUE TITLE
Error running on Ubuntu:SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by Hamza-101** [smartbugs/smartbugs#46]
I get the following error when running `python3 smartBugs.py --tool oyente --file dataset/reentrancy/simple_dao.sol
:`

`Traceback (most recent call last):
  File "smartBugs.py", line 13, in <module>
    from src.docker_api.docker_api import analyse_files
  File "/home/hamza/Downloads/smartbugs-master/src/docker_api/docker_api.py", line 3, in <module>
    import docker
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/transport/__init__.py", line 11, in <module>
    from .sshconn import SSHHTTPAdapter
  File "/home/hamza/.local/lib/python3.8/site-packages/docker/transport/sshconn.py", line 1, in <module>
    import paramiko
  File "/home/hamza/.local/lib/python3.8/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/hamza/.local/lib/python3.8/site-packages/paramiko/transport.py", line 65, in <module>
    from paramiko.sftp_client import SFTPClient
  File "/home/hamza/.local/lib/python3.8/site-packages/paramiko/sftp_client.py", line 41, in <module>
    from paramiko.sftp_file import SFTPFile
  File "/home/hamza/.local/lib/python3.8/site-packages/paramiko/sftp_file.py", line 66
    self._close(async=True)
                ^
SyntaxError: invalid syntax
`

**Comment by Hamza-101** [comment]
Running on ubuntu 20.04

**Comment by jff** [comment]
Thanks @Hamza-101

I cannot replicate this bug. It seems to be related with a local dependency. Perhaps you can try with a new virtual environment? Something like:

```
$ python3 -mvenv local-env
$ source local-env/bin/activate
$ pip install -r requirements.txt
```
And then try again:

```
$ python3 smartBugs.py --tool oyente --file dataset/reentrancy/simple_dao.sol
```

**Comment by Hamza-101** [comment]
I'll

**Comment by Hamza-101** [comment]
I'll try checking that.
