### ISSUE TITLE
Crash with socket timeout

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#72]
In the middle of a large test set, smart bugs crashed with the following trace:

```console
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "smartBugs.py", line 61, in analyse
    raise e
  File "smartBugs.py", line 44, in analyse
    analyse_files(tool, file, logs, output_folder, sarif_outputs, output_version, import_path, bytecode)
  File "/data-hdd/ethereum/tools/smartbugs/src/docker_api/docker_api.py", line 293, in analyse_files
    container = client.containers.run(image,
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/docker/models/containers.py", line 818, in run
    container.start()
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/docker/api/container.py", line 1110, in start
    res = self._post(url)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/data-hdd/ethereum/tools/smartbugs/venv/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "smartBugs.py", line 194, in <module>
    logs = exec_cmd(args)
  File "smartBugs.py", line 171, in exec_cmd
    pool.map(analyse, tasks)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
requests.exceptions.ReadTimeout: None: None
```

**Comment by gsalzer** [comment]
Can be closed once pull request #92 has been merged.
