### ISSUE TITLE
install instructions not working or unclear.

### ISSUE THREAD

**Issue by kylebakerio** [smartbugs/smartbugs#86]
cloned, installed requirements, tried to run example command from readme... nothing but a bunch of errors. :/

```bash
k@ubuntu-flavor-21.04:~/code/forks/smartbugs$ python3 /home/k/code/forks/smartbugs/smartBugs.py --tool all --file  ~/code/client-code/optilistic/audits/someproject/protocol/contracts/Artist.sol
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/home/k/.local/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/home/k/.local/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/k/.local/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/k/.local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/k/.local/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/k/.local/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/k/code/forks/smartbugs/smartBugs.py", line 13, in <module>
    from src.docker_api.docker_api import analyse_files
  File "/home/k/code/forks/smartbugs/src/docker_api/docker_api.py", line 30, in <module>
    client = docker.from_env()
  File "/home/k/.local/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/k/.local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/k/.local/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/k/.local/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

```

**Comment by kylebakerio** [comment]
clone and install commands were successful, and attempting to install requirements again just produces a list of statements that requirement is already met.

**Comment by gsalzer** [comment]
To narrow down the source of the problem, try the following.

```console
git clone https://github.com/smartbugs/smartbugs.git
cd smartbugs
# We set up a virtual environment, to avoid clashes with other python installations
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3 smartBugs.py --tool oyente --dataset reentrancy
```
This works for me. If it also does for you, then I'd try to start smartbugs on your specific sol file, but from this directory, to avoid that files are not found. Then try other tools instead of oyente. Maybe the problem is that some docker image cannot be loaded.

**Comment by nettrino** [comment]
I run into this and I simply did not have docker running, so perhaps we could update the script to check if the daemon is up to show the appropriate error message.

**Comment by gsalzer** [comment]
@tdurieux Looks like a good idea. Can we check that docker is running, or at least add this possible cause to the respective error messages?

**Comment by gsalzer** [comment]
Check whether docker is installed has been added in commit cd05fd2b89905af83aa5d7efa4e239b42fda9ed2
