### ISSUE TITLE
Please ignore/delete, wrong repo

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#90]
Let `0xcbe717fb2923f4226271cc4c1d5ef2c076fb3247.hex` be the bytecode at `https://etherscan.io/address/0xcbe717fb2923f4226271cc4c1d5ef2c076fb3247#code`.

```console
python conkas.py 0xcbe717fb2923f4226271cc4c1d5ef2c076fb3247.hex 
Analysing 0xcbe717fb2923f4226271cc4c1d5ef2c076fb3247.hex...
PHI instruction need arguments but 0 was given

Traceback (most recent call last):
  File "conkas.py", line 108, in main
    traces = sym_exec.execute()
  File "/data-nvme/ethereum/repos/conkas/sym_exec/symbolic_executor.py", line 51, in execute
    new_traces = self.__sym_exec_traces(traces_to_execute)
  File "/data-nvme/ethereum/repos/conkas/sym_exec/symbolic_executor.py", line 64, in __sym_exec_traces
    new_blocks = self.__sym_exec_block(block_to_analyse, trace.state)
  File "/data-nvme/ethereum/repos/conkas/sym_exec/symbolic_executor.py", line 93, in __sym_exec_block
    new_blocks = self.__sym_exec_instruction(instruction, state)
  File "/data-nvme/ethereum/repos/conkas/sym_exec/symbolic_executor.py", line 116, in __sym_exec_instruction
    return func(instruction, state)
  File "/data-nvme/ethereum/repos/conkas/sym_exec/instructions/rattle_instructions.py", line 58, in inst_phi
    raise Exception
Exception
```

**Comment by gsalzer** [comment]
Sorry, wrong repository, should have been Conkas
