### ISSUE TITLE
Maian analysis of source code broken with docker image solc4.25 7d2c0333607f: geth connection timeout

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#99]
When analyzing source code, Maian deploys the contract on a local blockchain. This is broken for docker image `solc4.25 7d2c0333607f`.

`python smartBugs.py -t maian --dataset access_control` generates `result.log` files like the one below. It seems that the connection to `geth` times out.
```console
====================================================================================================
[ ] Compiling Solidity contract from the file /data/arbitrary_location_write_simple.sol ...  Done
[ ] Connecting to PRIVATE blockchain emptychain  ... ESTABLISHED
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1242, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8550): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 120, in main
    if args.soliditycode:   contract_address = deploy_contract(args.soliditycode[1], MyGlobals.etherbase_account)
  File "/MAIAN/tool/contracts.py", line 87, in deploy_contract
    MyGlobals.web3.personal.unlockAccount(etherbase, '1', 15000)
  File "/usr/local/lib/python3.5/dist-packages/web3/personal.py", line 93, in unlockAccount
    [account, passphrase, duration],
  File "/usr/local/lib/python3.5/dist-packages/web3/manager.py", line 93, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.5/dist-packages/web3/manager.py", line 76, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.5/dist-packages/web3/middleware/formatting.py", line 25, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8550): Read timed out. (read timeout=10)
[ ] Deploying contract
====================================================================================================
```

**Comment by jff** [comment]
I confirm this error. The analysis was successful in some cases, but failed in most with the same error.

When running `python smartBugs.py -t maian --file dataset/access_control/arbitrary_location_
write_simple.sol` it also fails.

**Comment by gsalzer** [comment]
I'm currently working on an update of Maian, to use it with a current version of geth. Maybe this solves this problem as well.

**Comment by gsalzer** [comment]
I have updated Maian to work with current versions of web3, Python and geth, see https://github.com/smartbugs/MAIAN At least outside of docker, this version of Maian does not give these errors.

**Comment by gsalzer** [comment]
Related: issue https://github.com/smartbugs/smartbugs/issues/85

**Comment by gsalzer** [comment]
Has been resolved by an update of the docker images for Maian
